# Generated by Django 2.0.6 on 2019-11-08 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_aaa'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='sex',
            field=models.BooleanField(default=True),
        ),
    ]
